VC = iverilog
ifeq (Darwin,$(shell uname -s))
WAVETOOL=open
else
WAVETOOL=gtkwave
endif

all: $(TARGET)

$(TARGET): $(FILES)
	$(VC) $(VCFLAGS) -o $(TARGET) $(FILES)

run: $(TARGET)
	./$(TARGET)

wave: $(TARGET)
	@if [ -f "$(GTKW)" ]; then \
		./$(TARGET) ; \
		$(WAVETOOL) $(GTKW); \
	else \
		echo "please locate your gtkwave save file in GTKW variable"; \
	fi

clean:
	rm -f $(TARGET) *.vcd
