/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_juluos_sample_HelloJNI */

#ifndef _Included_org_juluos_sample_HelloJNI
#define _Included_org_juluos_sample_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_juluos_sample_HelloJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_juluos_sample_HelloJNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_juluos_sample_HelloJNI
 * Method:    sayHelloInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_juluos_sample_HelloJNI_sayHelloInC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_juluos_sample_HelloJNI
 * Method:    intMethod
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_juluos_sample_HelloJNI_intMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
